### ISSUE TITLE
Rendering egui to a plane/Camera2d

### ISSUE THREAD

**Issue by thedoctor3141** [mvlabat/bevy_egui#163]
I've been reading the source code and docs for a while, and I'm frankly lost. I don't want to change the gui component rendering, shaders, or asset management, I know I'll need to override the input, but from what I've read, that should be manageable. I just.. don't see how to create a context with the available render system, and restrict it to a specific Camera. Thanks for any assistance.

Side note: I did notice another topic wanting to render on top of egui. Restructuring the rendering in the manner described above might make that easier.

**Comment by aevyrie** [comment]
Right now it looks like egui always assumes it is rendering to a window, as it assumes it is tied to an `Entity` that has a `Window`:

https://github.com/mvlabat/bevy_egui/blob/537ec1b1fe6206042633bad6121745bf2e0ec1cb/examples/two_windows.rs#L26

Instead, it would probably need to be flipped, so that each egui context must be associated with a `Camera`, not a `Window`. Just like Bevy's rendering, egui would render to that `Camera`'s `RenderTarget`, which can be a `Window` or an `Image`. From there, you can apply that `Handle<Image>` to whatever you want - a plane or any arbitrary mesh.

**Comment by mvlabat** [comment]
Rendering UI to worldspace should now be possible (we still lack a proper input handling though, I'll probably fix this once Bevy 0.15 lands).
