### ISSUE TITLE
Closing main bevy window should close all egui windows

### ISSUE THREAD

**Issue by dimvoly** [mvlabat/bevy_egui#165]
Since upgrading to bevy 0.10 and bevy_egui 0.20, if I have an egui window open in bevy when I close the bevy window, the program panics:

	thread 'Compute Task Pool (0)' panicked at '`EguiContexts::ctx_mut` was called for an uninitialized context (primary window), make sure your system is run after [`EguiSet::InitContexts`] (or [`EguiStartupSet::InitContexts`] for startup systems)',

Would be great, if some clean up code would run on closing the bevy window so that this doesn't occur.

**Comment by mvlabat** [comment]
Hi! Thanks for filing the issue. I'm not sure if there's anything that can be fixed on the `bevy_egui` end. I've discovered that the `two_windows` example also panicked on closing the primary window, and the fix was basically to [assume that the window entity can be missing](https://github.com/mvlabat/bevy_egui/commit/dc4ae6859dba8c7494a4116107b83a3a5c5252b0) in the UI system itself.

Please let me know if that helps.

**Comment by dimvoly** [comment]
Thanks, following that example fixed it for me.

Reason I hit that issue is I was using this in my system parameters:

    mut egui_contexts: EguiContexts,

Looking at `EguiContexts`, there is no check for a primary window within. So thus I followed the two_windows example where this is the query:

    mut egui_ctx: Query<&mut EguiContext, With<PrimaryWindow>>,

And the context is pulled out of the query 

    let Ok(mut ctx) = egui_ctx.get_single_mut() else { return; };

Which exist the system if unsuccessful, avoiding the panic.

**Comment by Shatur** [comment]
Thanks for the info!
