### ISSUE TITLE
Feature Request: attach on entity or render to texture

### ISSUE THREAD

**Issue by afpro** [mvlabat/bevy_egui#193]
I want make ui in game with egui, like name plate or menu on the wall. any ideas?

**Comment by TheButlah** [comment]
I would also like to have world-space UIs. I think this could be accomplished with the ability to render to a bevy image as an output texture. I've managed to do something similar with bevy_wgpu here ([WIP code](https://github.com/TheButlah/wgpu-experiments/commit/abc18093223deec5686ad5d1432d05422f49a6be), danger).

Is there any interest in adding this as a feature to bevy_egui?

**Comment by flash-freezing-lava** [comment]
I am not sure what is meant by "attach on entity".
If you want to draw a nameplate UI at a world-coordiate without rotation, reflection, or any other 3D processing, this can be done with `world_to_viewport` and `Area` (see below).
The second feature (drawing a menu on a wall, so that it is post-processed by 3D systems) would require drawing UI to texture like @TheButlah did, translating mouse clicks back by ray-casting the click position to the object, and then using the intersection point of ray and object to calculate what 2D coordinate in the local space of the UI was clicked. Especially the interactive version seems very complicated.

# Drawing an egui UI above an entity (f.e. a nameplate)

The steps to do this are:
1. Get the 3D position of the entity with [`GlobalTransform`](https://docs.rs/bevy/latest/bevy/prelude/struct.GlobalTransform.html). Make sure to call this after the [`TransformPropagate`](https://docs.rs/bevy/0.11.0/bevy/transform/enum.TransformSystem.html#variant.TransformPropagate) system set.
2. Translate it to the screen positon with [`Camera.world_to_viewport`](https://docs.rs/bevy/latest/bevy/render/camera/struct.Camera.html#method.world_to_viewport)
3. Create an [`Area`](https://docs.rs/egui/0.22.0/egui/containers/struct.Area.html) with [fixed position](https://docs.rs/egui/0.22.0/egui/containers/struct.Area.html#method.fixed_pos)

The code below is what I use, to draw the name of a character above it, as seen in following picture:
![character with name writter above the head](https://i.imgur.com/ID6h9xG.png)

```rust
/// Returns a position, that is above and behind the player, in screen coordinates.
/// If the entity is outside of the viewport, this returns a position with X outside of [0.0, viewport_width] or Y outside [0.0, viewport_height].
/// May return `None` if the entity is culled because it is too far or close, or if there is no viewport.
fn get_nameplate_pos(
    camera: &Camera,
    camera_transform: &GlobalTransform,
    player_transform: &GlobalTransform,
    player_collider: &Collider,
) -> Option<Pos2> {
    let head_radius = get_player_head_radius(player_collider);
    let (_player_radius, player_height) = get_player_radius_and_height(player_collider);
    let nameplate_back_pos = player_transform.translation() + Vec3::new(0.0, player_height, -head_radius);
    let nameplate_center_pos = player_transform.translation() + Vec3::new(0.0, player_height, 0.0);
    let y = camera.world_to_viewport(camera_transform, nameplate_back_pos)?.y;
    let x = camera.world_to_viewport(camera_transform, nameplate_center_pos)?.x;
    Some(pos2(x, y))
}

fn draw_nameplate_at(ui: &mut Ui, screen_pos: Pos2, nameplate_text: String) {
    let font_id = FontId::proportional(NAME_PLATE_TEXT_SIZE);
    // calculate the required size of the nameplate
    let nameplate_rect = ui.fonts(|fonts| {
        fonts
            .layout(nameplate_text.clone(), font_id.clone(), NAME_PLATE_COLOR, f32::MAX)
            .rect
    });
    Area::new(Id::new(("Nameplate", &nameplate_text)))
        .fixed_pos((screen_pos.x - nameplate_rect.width() / 2.0, screen_pos.y - nameplate_rect.height()))
        .interactable(false)
        .movable(false)
        .show(ui.ctx(), |ui| {
            ui.style_mut().wrap = Some(false);
            ui.visuals_mut().widgets.noninteractive.fg_stroke.color = NAME_PLATE_COLOR;
            ui.label(RichText::new(nameplate_text).font(font_id));
        });
}

```

**Comment by TheButlah** [comment]
Sounds like there are two separate issues here. I'll make a new issue for the world-space UI.

**Comment by afpro** [comment]
#207 is my goal too, 'text on screen space' just can be done with bevy native ui system.
