### ISSUE TITLE
Implementing `Into<&Context> for &egui::context::Context` to avoid type mismatch

### ISSUE THREAD

**Issue by marlalain** [mvlabat/bevy_egui#255]
I can't pass the necessary context due to a type mismatch when using a library like [egui-notify](https://github.com/ItsEthra/egui-notify). Having a way to change it would be beneficial. It would also help anyone porting an existing codebase to bevy and bevy_egui.

**Comment by mvlabat** [comment]
Hey! You can get `&egui::context::Context` by calling this method: https://docs.rs/bevy_egui/latest/bevy_egui/struct.EguiContexts.html#method.ctx_mut

I'd like to keep it this way (without adding the `Into` implementation) so that people are aware of the immutable and mutable methods distinctions, the window API, etc.

**Comment by marlalain** [comment]
I tried using `ctx_mut,` but the compiler tells me there's a mismatch between bevy_egui's Context and egusi's Context. am I doing something wrong? sorry if that's a newbie question, I never saw this before

**Comment by mvlabat** [comment]
Oh, make sure the `egui` versions match. We haven't yet updated `bevy_egui` to support Egui 0.25. I guess you should use `egui-notify 0.11`.

**Comment by marlalain** [comment]
That must be it. Thanks!
