### ISSUE TITLE
Text input doesn't bring up virtual keyboard on mobile

### ISSUE THREAD

**Issue by stmdhms** [mvlabat/bevy_egui#29]
This was recently fixed in egui itself (https://github.com/emilk/egui/pull/247), but doesn't currently work correctly in bevy_egui.

**Comment by OfficialURL** [comment]
This would be solved by #27.

**Comment by mvlabat** [comment]
I'm afraid just upgrading to 0.12 doesn't fix it. I guess we need to port the changes that were done in https://github.com/emilk/egui/pull/253 do `bevy_egui`. Unfortunately, I'm not able to look into those atm myself, but I'm happy to accept a PR if anyone wants to tackle that.

**Comment by miketwenty1** [comment]
Is it still possible to bring up the mobile keyboard with a WASM build?

**Comment by mvlabat** [comment]
Still impossible, unfortunately. If anyone wants to make a PR for this, I'll gladly accept it.

**Comment by oscrim** [comment]
Hello, Ive been working on this on [this branch](https://github.com/oscrim/bevy_egui/tree/touch-and-text-input) (which also containts the work from #180 ). Due to winit lacking support for composition events in the web (as can be seen [here](https://github.com/rust-windowing/winit/issues/1497)) I excluded the event listeners for them as it currently sends them all out at once when the composition ends which causes unwanted behavior.

**Comment by v-kat** [comment]
@oscrim did your code fix mobile keyboard issues with bevy_egui? I wasn't sure if this was an IME issue that has to be explored at a lower level.

**Comment by oscrim** [comment]
It was more of a work around than a proper fix. It's been a while since I looked at it

**Comment by v-kat** [comment]
Do you think it's something you could eventually upstream? I was still trying to understand if there was a bug in IME somewhere or if some of the code from egui needed to be adapted/bridged to bevy. (Maybe from https://github.com/emilk/egui/blob/master/crates/eframe/src/web/text_agent.rs )

**Comment by v-kat** [comment]
I might just steal your code and maybe try to upstream it >.>

**Comment by mvlabat** [comment]
Implemented in bevy_egui 0.30
