### ISSUE TITLE
Can a `Res<EguiContext>` be used in two parallel systems?

### ISSUE THREAD

**Issue by OfficialURL** [mvlabat/bevy_egui#32]
This is more of a question than an issue. In my application, I currently have various parallel systems showing different windows. Most times they work just fine, but they occasionally provoke a startup crash, so I wonder if this is a limitation or a bug.

The first few lines of the startup crash error message:
```
thread 'main' panicked at 'already mutably borrowed', C:\Users\vi\.cargo\registry\src\github.com-1ecc6299db9ec823\atomic_refcell-0.1.7\src\lib.rs:151:23
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\panicking.rs:493
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\core\src\panicking.rs:92
   2: core::panicking::panic_str
             at C:\Users\vi\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\panicking.rs:57
   3: atomic_refcell::AtomicRefCell<egui::memory::Memory>::borrow_mut<egui::memory::Memory>
             at C:\Users\vi\.cargo\registry\src\github.com-1ecc6299db9ec823\atomic_refcell-0.1.7\src\lib.rs:151
   4: epaint::mutex::Mutex<egui::memory::Memory>::lock
             at C:\Users\vi\.cargo\git\checkouts\egui-5e4507fa4153be06\effd3c7\epaint\src\mutex.rs:144
   5: egui::context::Context::memory
             at C:\Users\vi\.cargo\git\checkouts\egui-5e4507fa4153be06\effd3c7\egui\src\context.rs:378
   6: egui::context::Context::style
             at C:\Users\vi\.cargo\git\checkouts\egui-5e4507fa4153be06\effd3c7\egui\src\context.rs:443
   7: egui::containers::window::{{impl}}::show_impl::{{closure}}
             at C:\Users\vi\.cargo\git\checkouts\egui-5e4507fa4153be06\effd3c7\egui\src\containers\window.rs:255
   8: core::option::Option<egui::containers::frame::Frame>::unwrap_or_else<egui::containers::frame::Frame,closure-0>
             at C:\Users\vi\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\option.rs:427
   9: egui::containers::window::Window::show_impl
             at C:\Users\vi\.cargo\git\checkouts\egui-5e4507fa4153be06\effd3c7\egui\src\containers\window.rs:255
  10: egui::containers::window::Window::show<closure-0>
             at C:\Users\vi\.cargo\git\checkouts\egui-5e4507fa4153be06\effd3c7\egui\src\containers\window.rs:236
```

**Comment by mvlabat** [comment]
Hi @OfficialURL! Oh, when I looked at egui's `Context`, I saw it wrapped its fields into mutexes, so I assumed it's totally fine to be used in parallel out of the box. Just now I've noticed that it uses its own wrapper around `parking_lot`'s `Mutex`, which panics if it's built with `egui/single_threaded` feature (which is the default one). Please try to disable this one, enable `egui/multi_threaded` and see whether it works.

We should probably build `egui` with `multi_threaded` by default since the current API implies using the context in multiple threads. And it would be nice to introduce a feature in `bevy_egui` to switch back to the default `egui/single_threaded`, also documenting that our context should be accessed only via `ResMut<EguiContext>` when using it.

**Comment by mvlabat** [comment]
I decided not to add the feature for the following two reasons:
1. Enabling the single-threaded mode would require a user to disable all the default features.
2. Egui doesn't quite advertise multi-threaded usage, so I think that a safer default is the single-threaded mode.

From Egui's documentation:
```
/// Almost all methods are marked `&self`, `Context` has interior mutability (protected by mutexes).
/// Multi-threaded access to a [`Context`] is behind the feature flag `multi_threaded`.
/// Normally you'd always do all ui work on one thread, or perhaps use multiple contexts,
/// but if you really want to access the same Context from multiple threads, it *SHOULD* be fine,
/// but you are likely the first person to try it.
```

I tried to improve our documentation instead, to mitigate the confusion: 83b84cec364075a893d256a28da0c1aada374f68.

Please feel free to reopen the discussion if you disagree or aren't quite happy with the decision. I'm open to other arguments and might still reconsider it.

**Comment by frewsxcv** [comment]
Thoughts on revisiting this? It looks like the egui is multi-threaded by default and the context can be freely cloned now.

https://github.com/emilk/egui/commit/15254f8235e5905b1c61c9f29aff30ce22db8141

https://github.com/emilk/egui/commit/8ce0e1c5206780e76234842b94ceb0edf5bb8b75#diff-6593d7c63c5e66f9c0c1cd121186d9ebbde6eb4fc86b0396d5ffd93ac9788377R125

**Comment by mvlabat** [comment]
@frewsxcv you can use the `immutable_ctx` feature to be able to access the context in parallel. Though I usually encourage people to keep relying on the Bevy scheduler, since you can't really use Egui context truly in parallel anyway, as its internals is hidden behind `RwLock`. Accessing the Egui context by two systems at once will just cause one of the systems busy waiting for the lock to be released. By accessing the context with `ResMut` you'd let the Bevy scheduler do other useful work.
